---
title: "sciPENN plots"
output: html_document
date: '2022-12-16'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Seurat)
# BiocManager::install("zellkonverter")
library(zellkonverter)
library(ggplot2)
library(SingleCellExperiment)
library(dplyr)
library(patchwork)
```

```{r embedding UMAP}
# read in embedding and predictions generated by sciPENN in python
sciEmbedding <- zellkonverter::readH5AD('/home/asmauger/biostat625final/embedding.h5ad')

# make seurat object to store these (based on full data)
sparse_RNA = readRDS('/home/asmauger/biostat625final/sparse_RNA.rds')
sparse_prot = readRDS('/home/asmauger/biostat625final/sparse_prot.rds')
metadata = read.csv('/home/asmauger/biostat625final/metadata.csv', header=T)
rownames(metadata) = metadata[,1]
# add RNA and metadata
seuratobj = CreateSeuratObject(counts = sparse_RNA, meta.data=metadata)
# add raw protein
prot_assay = CreateAssayObject(counts=sparse_prot)
seuratobj[['prot']] = prot_assay

# add sciPENN embedding
sciEmbedding <- assay(sciEmbedding, "X")
sciEmbedding <- t(sciEmbedding)
seuratobj[['scipenn']] <- CreateAssayObject(counts = sciEmbedding)

# do PCA and UMAP
VariableFeatures(seuratobj, assay='scipenn') <- 0:511
seuratobj <- ScaleData(seuratobj, assay='scipenn')
seuratobj <- RunPCA(seuratobj, assay='scipenn')
ElbowPlot(seuratobj)
seuratobj <- RunUMAP(seuratobj, dims = 1:20)
DimPlot(seuratobj, reduction = "umap", group.by='cell_type', shuffle = T)

# add 'test/train' indicator 

sparse_prot_train = readRDS('/home/asmauger/biostat625final/sparse_prot_train.rds')
training_cells = colnames(sparse_prot_train)
all_cells = colnames(sparse_prot)
train_indicate = all_cells %in% training_cells

seuratobj <- AddMetaData(seuratobj, train_indicate, col.name="training.indicator")


overall_umap <- DimPlot(seuratobj, reduction = "umap", group.by='training.indicator', shuffle = T) 

saveRDS(overall_umap, file='/home/asmauger/biostat625final/overall_umap.rds')
```

```{r protein prediction UMAP}
protein_predictions <- zellkonverter::readH5AD('/home/asmauger/biostat625final/protein_test_final.h5ad')

# initialize seurat object 
sparse_prot_test = readRDS('/home/asmauger/biostat625final/sparse_prot_test.rds')
seuratobj2 = CreateSeuratObject(counts = sparse_prot_test, meta.data=metadata)

# extract scaled 'true' protein
scaled_true <- assay(protein_predictions, 'logcounts')
# extract predictions
predicted <- assay(protein_predictions, 'imputed')
# extract unscaled 'true' protein
true <- assay(protein_predictions, 'counts')

# min-max normalization (force between 0 and 1)
predicted2 <- apply(predicted, 1, function(x) (x-min(x))/(max(x)-min(x)))
predicted2 <- t(predicted2)
scaled2 <- apply(scaled_true, 1, function(x) (x-min(x))/(max(x)-min(x)))
scaled2 <- t(scaled2)

# add to seurat
seuratobj2[['counts']] <- CreateAssayObject(counts = true)
seuratobj2[['scaledcounts']] <- CreateAssayObject(counts = scaled_true)
seuratobj2[['predicted']] <- CreateAssayObject(counts = predicted)
seuratobj2[['scaled2']] <- CreateAssayObject(counts = scaled2)
seuratobj2[['predicted2']] <- CreateAssayObject(counts = predicted2)

# do PCA and UMAP
VariableFeatures(seuratobj2, assay='counts') <- rownames(seuratobj2[['counts']]) # take all proteins
seuratobj2 <- ScaleData(seuratobj2, assay='counts')
seuratobj2 <- RunPCA(seuratobj2, assay='counts')
ElbowPlot(seuratobj2)
seuratobj2 <- RunUMAP(seuratobj2, dims = 1:20)
cell_typeplot <- DimPlot(seuratobj2, reduction = "umap", group.by='cell_type', shuffle = T)

DefaultAssay(seuratobj2) <- 'predicted2'
predictedplots <- FeaturePlot(seuratobj2, features = c('CD328', "CD8", "CD71", 'CD62L'), keep.scale='feature')

DefaultAssay(seuratobj2) <- 'scaled2'
trueplots <- FeaturePlot(seuratobj2, features = c('CD328', "CD8", "CD71", 'CD62L'))

cell_typeplot
predictedplots
trueplots

saveRDS(cell_typeplot, '/home/asmauger/biostat625final/protein_celltype_umap.rds')
saveRDS(predictedplots, '/home/asmauger/biostat625final/protein_predicted_umap.rds')
saveRDS(predictedplots, '/home/asmauger/biostat625final/protein_true_umap.rds')
```
